### ISSUE TITLE
README.md requires an update

### ISSUE THREAD

**Issue by chrisganov** [hyphone/asus-g14-fedora#10]
Currently you have added that once you copy etc and usr are done, we should update the systemctl - however the name of the file is wrong in the doc. The actual name is "asusctl_hibernate.service" while you have indicated "asus_hibernate.service"

**Comment by marcolaux** [comment]
thanks for letting me now - this guide was waaaay out of date.
so many things are in the kernel or upstream now (fan curves, power profiles vie powerprofilectl).

I updated the guide here to reflect this. now it's just a bit of a preference for the cursor keys.
