### ISSUE TITLE
[Not an issue] Add info to Readme

### ISSUE THREAD

**Issue by eugenov** [hyphone/asus-g14-fedora#3]
Hello! Could you add some info about:
1. GPU switching, preferable way
2. How do you launch gpu apps?
3. Is gpu offloading working?
Thank you for your work!

**Comment by marcolaux** [comment]
Hi there

at the moment I suggest only one way of switching, via asusctl or the GNOME Shell extension (that also uses asusctl).

I added some information about the switching, the GNOME Shell extension and asusctl.

What do you think?

**Comment by eugenov** [comment]
Good! Special TY for explanation of graphic modes - it is not too obvious in other sources.
Is there any need to logout/reboot after switching?

**Comment by marcolaux** [comment]
when you use the console to switch via asusctl it will tell you

when you use the extension in this repo the icon of a red circle appears that indicates that you need to reboot.

I'm planning to add more information to the extension in the future when I have time.

**Comment by marcolaux** [comment]
I now added a reboot notification with a call to action to reboot or restart Xorg

![grafik](https://user-images.githubusercontent.com/6410852/106669281-b8d96500-65ab-11eb-9e1e-adbd0126587d.png)
