### ISSUE TITLE
Add home/end/insert hotkeys

### ISSUE THREAD

**Issue by eugenov** [hyphone/asus-g14-fedora#4]
Hi! Please add
- hotkeys for "home"/"end" -> fn+"left"/"right"
- _any_ hotkeys for "insert"

**Comment by marcolaux** [comment]
Hi and thanks for the suggestion - what do you mean by _any_ hotkey for insert?

**Comment by eugenov** [comment]
I mean any hotkey with fn-key (f.e. fn+i), since we have no free arrow keys left :)
Oh, is these hotkeys replace "pg up", "pg down", "home", "end" or I still able to use them on usb keyboard?

**Comment by marcolaux** [comment]
I'm currently not sure how I could map fn+any key as keyscanners don't give me an unique keycode for this (for example fn+i). I propably would have to override another fn+key combination.

Other keyboards should work fine and unmodified as the modifications are for the internal keyboard alone (gets identified by it's unique ID)

**Comment by eugenov** [comment]
TY, let's close this issue, as hotkeys implemented. But still hoping for "insert".
