### ISSUE TITLE
External displays

### ISSUE THREAD

**Issue by eugenov** [hyphone/asus-g14-fedora#7]
Is there special configs for offloading nvidia on external displays? DP, hdmi?
Thank you!

**Comment by marcolaux** [comment]
The Nvidia is wired to the USB-C when in Nvidia mode. This post directly gets its output from there.
For hybrid mode have a look here: https://asus-linux.org/faq/#graphics-and-switching

**Comment by eugenov** [comment]
There is no such info inside the link... Just basic troubleshooting

**Comment by marcolaux** [comment]
Personally I just use the HDMI and offload with the NVIDIA and live with the eventual tearing.
The USB-C I just use for VM with GPU passthrough.

The NVIDIA mode of asusctl I don't use at all but should work out of the box with the USB-C port then.
If not and you get a black screen have a look in the link.

**Comment by marcolaux** [comment]
> There is no such info inside the link... Just basic troubleshooting

there is:
### Why did nvidia mode give me black screen with xorg?

This happens on AMD machines typically, if your machine is AMD then you need to add the following to run on graphical login:

```
xrandr --setprovideroutputsource modesetting NVIDIA-0
xrandr --auto
```

there are many ways to do this so you will need to search for the right way for your login manager.

**Comment by marcolaux** [comment]
this repo are just my personal files and my setup how I configured this machine for my use case.

If you have questions beyond that, like this one, I recommend that you join the discord:
https://discord.gg/ngbdKabAnP

**Comment by eugenov** [comment]
> Why did nvidia mode give me black screen with xorg?

This question is because I often face igpu rendering on hdmi external display. No black screens, just baaaad perf (nvidia-smi ok).

> Personally I just use the HDMI and offload with the NVIDIA and live with the eventual tearing.

Did you try Synchronized RandR Outputs to prevent tearing? (https://download.nvidia.com/XFree86/Linux-x86_64/460.56/README/randr14.html)

**Comment by marcolaux** [comment]
> This question is because I often face igpu rendering on hdmi external display. No black screens, just baaaad perf (nvidia-smi ok).

the HDMI is wired to the iGPU so the output of the iGPU is output there

**Comment by marcolaux** [comment]
> Did you try Synchronized RandR Outputs to prevent tearing? (https://download.nvidia.com/XFree86/Linux-x86_64/460.56/README/randr14.html)

no. I don't game much on it. I use the dGPU mostly for CUDA applications like Darktable.

**Comment by eugenov** [comment]
> the HDMI is wired to the iGPU

Windows has no problems there - so issue is with configs and/or linux nvidia driver. But thanks for info!

**Comment by marcolaux** [comment]
not sure why you have bad performance. offloading with the nvidia and rendering it through the internal display or HDMI works perfectly fine for me
