### ISSUE TITLE
Kernel modules?

### ISSUE THREAD

**Issue by mgarofano80** [hyphone/asus-g14-fedora#8]
Hi! I saw you just removed the kernel folder and added the lukenukem/asus-linux custom kernel. I had manually added your kernel modules from a few days ago (that worked great in making my 2021 G14 trackpad and wake from sleep work). At the time, I noticed though that - I am on rawhide - one of them was replacing a previous kernel module, that I had to update back to the newer one supplied in rawhide (the other kernel modules didn't. Would now using the lukenukem/asus-linux kernel be safe in rawhide too? I am forced to use rawhide because of some openvpn3 issues that have only been fixed there.

**Comment by mgarofano80** [comment]
Sì

> Hi! I saw you just removed the kernel folder, which contained modules to fix the trackpad and wake from sleep issues. May I ask why? They served exactly that purpose, made my G14 trackpad work smoothly and also avoided the freeze when the laptop awakes from sleep. I also wanted to ask if you could make those modules compatible with rawhide, which I am using. They work, but one of them was attempting to replace a component with an older version, which, in turn, I updated to the current rawhide version again.

**Comment by marcolaux** [comment]
Hi there!
It looks like that Luke also compiles it for Rawhide:
https://copr.fedorainfracloud.org/coprs/lukenukem/asus-linux/

But I'm not able to confirm at this moment if a new Rawhide kernel will not override the ones from there.
Perhaps when doing upgrades, use DNF and have a look that no other than a **rog**-marked kernel gets installed. If DNF wants to update to a newer, not rog-kernel, then perhaps it's a good idea to wait until the kernel in the Copr is updated and picked up.

**Comment by mgarofano80** [comment]
> Hi there!
> It looks like that Luke also compiles it for Rawhide:
> https://copr.fedorainfracloud.org/coprs/lukenukem/asus-linux/
> 
> But I'm not able to confirm at this moment if a new Rawhide kernel will not override the ones from there.
> Perhaps when doing upgrades, use DNF and have a look that no other than a **rog**-marked kernel gets installed. If DNF wants to update to a newer, not rog-kernel, then perhaps it's a good idea to wait until the kernel in the Copr is updated and picked up.

I gladly volunteered to try that out and I can report it works flawlessly. I installed that on top of your previous kernel modules from last week, refreshed, reboot and all mods were preserved while no exceptions were thrown. Keep up the great work, thank you!
