### ISSUE TITLE
Graphics mode not initialized

### ISSUE THREAD

**Issue by Mundo-Dev0ps** [hyphone/asus-g14-fedora#9]
Hello Everyone,

I have a issue with nvidia profile, i cant selected 
![image](https://user-images.githubusercontent.com/47090182/116256187-f3811280-a740-11eb-9d45-45ca221a3e69.png)

```bash
asusctl graphics -m nvidia
```
![image](https://user-images.githubusercontent.com/47090182/116256593-54104f80-a741-11eb-9823-1f96e3046ccf.png)

![image](https://user-images.githubusercontent.com/47090182/116256821-891ca200-a741-11eb-9324-004e48378c57.png)
![image](https://user-images.githubusercontent.com/47090182/116256870-9174dd00-a741-11eb-85f3-ea7e48f4ffb2.png)

Installed
![image](https://user-images.githubusercontent.com/47090182/116256257-072c7900-a741-11eb-9915-d69d70ae84e5.png)

Kernel:
![image](https://user-images.githubusercontent.com/47090182/116256278-0d225a00-a741-11eb-9e7d-6de555197c6f.png)

Grup:
![image](https://user-images.githubusercontent.com/47090182/116256434-2f1bdc80-a741-11eb-8f60-2521482d35f6.png)

Can anyone help me?
Regards

**Comment by marcolaux** [comment]
the message basically implies that the dbus method of asusd for graphics switching is not available.

can you try to use this version?
https://gitlab.com/asus-linux/asusctl-gex/-/tree/1.0.0-rc2

first remove the extension in /usr/share/gnome-shell/extensions/
clone the repo above
run make and make install (not with sudo), restart the shell and try again

I'll update the extension asap.

**Comment by marcolaux** [comment]
things to check as well:
- rebooted after the nvidia driver is installed?
- what does `asusctl graphics -g` output?
- logged out after switch?

**Comment by Mundo-Dev0ps** [comment]
Hello @hyphone ,

Ty for reply

I execute the steps
![image](https://user-images.githubusercontent.com/47090182/116281850-1a970e80-a758-11eb-8f4f-c654fee3fdd5.png)
![image](https://user-images.githubusercontent.com/47090182/116281878-2387e000-a758-11eb-9c6a-96a4b8f67369.png)

After logout but not working

and 
```bash
asusctl graphics -g
```
![image](https://user-images.githubusercontent.com/47090182/116282301-95f8c000-a758-11eb-989b-0ea6a304bd1f.png)

uhmm i think this is problem with nvidia controller
![image](https://user-images.githubusercontent.com/47090182/116282508-db1cf200-a758-11eb-8103-e34ac1a122c1.png)

**Comment by Mundo-Dev0ps** [comment]
After reboot

i saw 1 more controler 
![image](https://user-images.githubusercontent.com/47090182/116283032-71e9ae80-a759-11eb-9daa-7bac082ecca1.png)

Logs
![image](https://user-images.githubusercontent.com/47090182/116283191-99d91200-a759-11eb-9ac1-5b030a581821.png)

**Comment by marcolaux** [comment]
kmod gets created by the nvidia driver. that's what the "akmod" package is for. it compiles the nvidia driver everytime a new kernel gets installed.

you tried to remove the system extension without sudo. please try again with superuser privileges.

did you also logout after you did the gfx switch? when it's written logout, you have to logout.

so the problem in the extension describes that it can't connect to the dbus interface of asusd.

let's then have a look if the graphics switching works in general and forget about the gnome shell extension for a moment:

`asusctl graphics -g`
what does this output?

switch to another mode:
`asuctl graphics -m nvidia` (or use something else if you are already on nvidia mode)
after logout and logoin again what does `asusctl graphics -g` now say?

if it is nvidia and this command prints that the nvidia module is loaded, it should work:
`lsmod | grep nvidia`

**Comment by marcolaux** [comment]
if the gfx switching in general does not work for you I suggest you join the discord channel:
https://discord.gg/ngbdKabAnP

and / or post an issue here:
https://gitlab.com/asus-linux/asusctl
